_includes/concepts/supported_services.html

We're supporting same day delivery through Liefery. This PR adjusts the supported services table on the concepts page accordingly.

adding liefery to supported services

---

_includes/concepts/webhooks_legend.html
_includes/navs/concepts_nav.html
concepts/index.md

Adds documentation for webhooks

added webhooks to concept page

---

_includes/navs/reference_nav.html
_includes/reference/shipment_quotes_request_parameters.md
_includes/reference/shipment_quotes_request_togglebox.html
_includes/schemas/shipment_quotes_request.json
_includes/schemas/shipment_quotes_response.json
_includes/shipment_quotes_post_request.json
_includes/shipment_quotes_post_response.json
_sass/_layout.scss
reference/index.md
reference/shipment_quotes_request_schema.md
reference/shipment_quotes_response_schema.md
schemas/shipment_quotes_request.json

* adds documentation for shipment quotes
* marks rates endpoint as deprecated

adds documentation for shipment quotes

---

_includes/schemas/shipments_request.json

* adds phone attribute to address
* adds description for returns service

updates shipments request schema

---

_includes/concepts/carrier_specific_field_lengths_dhl.md
_includes/concepts/carrier_specific_field_lengths_dpd.md
concepts/index.md

I've added the carrier specific field lengths from the dpd documentation

add dpd carrier specific field lengths

---

_includes/navs/concepts_nav.html
concepts/index.md

adds documentation how parameters should be send and which Content-Type to use to
the the concepts section.

adds documentation for parameters to concepts section

---

_includes/head.html
_includes/header.html
_includes/navs/recipes_nav.html
_includes/samples/curl.html
_layouts/default.html
_layouts/full.html
_sass/_base.scss
_sass/_layout.scss
recipes/index.md

Our examples section isn't the right place to show more complex processes. Therefore we're introducing a new recipes section.

add recipes section

---

_includes/navs/recipes_nav.html
_includes/recipes/declared_value_dhl.md
recipes/index.md

This PR gives more detailed info about higher insurance when using DHL as carrier

added info about higher insurance

---

_includes/navs/concepts_nav.html
_includes/navs/recipes_nav.html
_sass/_base.scss
concepts/index.md
recipes/index.md

Detailed description of how you can create shipments that are being send to a pakadoo point

using pakadoo

---

_includes/reference/shipments_request_parameters.md
_includes/samples/curl.html

also added 2 examples for the package types (DHL bulky items & DPD parcel letter) we're currently supporting

added package_type documentation

---

_includes/schemas/shipment_quotes_request.json
_includes/shipment_quotes_post_request.json
reference/index.md

- Removed a comma from the shipment quotes request json example
- fixed link to shipment quotes request json schema
- added "liefery" as carrier and "same_day" as service to shipment quotes request json schema

minor changes to fix / update shipment quotes documentation

---

_includes/navs/recipes_nav.html
_includes/samples/curl.md
recipes/index.md

the example page should only be used for basic examples in different programming languages
also added info about having to use your own carrier contract for sending bulky items

moved dhl bulk example to recipes

---

_includes/navs/recipes_nav.html
_includes/samples/curl.md
recipes/index.md

as with the bulk example it's more logical to have it be explained as a recipe

moved dpd parcel letter example to recipes

---

reference/index.md

I've also changed the description a bit to be more precise about what you can do

added a simpler example for a pickup request

---

_includes/navs/recipes_nav.html
recipes/index.md

Since we don't have a clear example how return shipments are created I've added a recipe for doing just that.

added a recipe for returns

---

_includes/pickup_post_requests_request.json
_includes/pickup_post_requests_response.json
reference/index.md

* dhl does not support pickup requests via web service

use dpd in pickup request example:

---

_includes/reference/shipments_request_parameters.md
_includes/schemas/shipments_request.json

also corrected the info about the description parameter at the package level

added info about the description parameter at the shipment level

---

concepts/index.md

We've got a shiny new integration guide.

adjusted concepts page with integration guide

---

_includes/reference/pickup_requests_request_parameters.md
_includes/reference/pickup_requests_request_togglebox.html
_includes/schemas/pickup_requests_request.json
_includes/schemas/pickup_requests_response.json
reference/index.md
reference/pickup_requests_request_schema.md
reference/pickup_requests_response_schema.md

we're using the parameter "pickup_time" for pickup requests now since this way we can define pickup windows
adjusted the json schema for the request and added a json schema for the response

added new definition of pickup time to JSON schema

---

_includes/navs/recipes_nav.html
recipes/index.md

since we're now supporting advance notice via dhl

restructure advance notice recipes

---

index.html
recipes/index.md

[postman](https://www.getpostman.com) now has a [*"run in postman" feature*](http://blog.getpostman.com/2016/03/10/run-button-is-live/). This adds a button to our website through which you can add a postman collection to your postman app and start making requests to our api right away.

added run in postman

---

_includes/concepts/carrier_specific_field_lengths_ups.md
reference/index.md

added UPS pickup request specs

added more info about carrier specific field lengths

---

_includes/reference/shipments_request_parameters.md

to shipments "parameter description (POST/PUT)"

added info about additional services

---

API_CHANGELOG.md

With our current release we added and fixed some stuff with our api. Updated the changelog to reflect those changes.

update changelog to 20160511

---

_includes/navs/concepts_nav.html
concepts/index.md

Added info for UPS and Hermes for now. tbc.

adding info about carrier cutoff times for pickups

---

_config.yml

all new shiny things in our integration guide 😜

update integration guide to v0.7

---

_config.yml
concepts/index.md
index.html

- moved integration guide and concepts under this category
- added a link to the German integration guide
- added link to newsletter archive

reworked getting started area on start page

---

_includes/concepts/additional_services.html
_includes/navs/examples_nav.html
_includes/schemas/shipments_request.json
examples/index.md

[Trello 86](https://trello.com/c/JVHMZ1iP)

Adds example for DHL delvivery time

---

_includes/concepts/other_attributes.html
_includes/navs/examples_nav.html
_includes/reference/shipments_request_parameters.md
_includes/schemas/shipments_request.json
_includes/shipments_post_put_request.json
examples/index.md

be more clear about DHL additional insurance

---

_config.yml
_includes/concepts/additional_services.html
_includes/concepts/carrier_specific_label_sizes.html
_includes/concepts/footnotes.html
_includes/concepts/other_attributes.html
_includes/concepts/package_types.html
_includes/concepts/supported_services.html
concepts/index.md

Liefery changed their offering, but it's not compatible with our services any more. Therefore we're removing it and leaving a note for developers.

remove Liefery and leave note for developers

---

_includes/concepts/additional_services.html
_includes/concepts/other_attributes.html
_includes/concepts/package_types.html
_includes/concepts/supported_services.html
_includes/navs/concepts_nav.html
_includes/navs/examples_nav.html
_sass/_base.scss
_sass/_layout.scss
concepts/index.md
css/main.scss
examples/index.md

also add abstract entries for saturday delivery and cash on delivery entries on example page
fix for jumping to correct id in code based on https://github.com/twbs/bootstrap/issues/1768#issuecomment-46519033

rework displaying additional services

---

_includes/navs/examples_nav.html
examples/index.md

also introduce the entry "additional insurance" to give an overview of the feature

add ups declared value

---

_includes/concepts/supported_services.html
_includes/navs/examples_nav.html
examples/index.md

added an example for the service Deutsche Post Warenpost

add Deutsche Post Warenpost

---

_includes/concepts/carrier_specific_field_lengths_gls_uniship.md
_includes/concepts/carrier_specific_field_lengths_gls_web_api.md
concepts/index.md

Added GLS specific field lengths for Uniship as well as the Web API

add gls specific field lengths

---

API_CHANGELOG.md
_includes/navs/examples_nav.html
_includes/schemas/shipments_request.json
examples/index.md

- Bulk shipments
- Customer alert
- IdentService
- ParcelShopDeliveryService
- Returns

added info about new Hermes (HSI) services and additional services

---

_includes/concepts/package_types.html
_includes/navs/examples_nav.html
examples/index.md

with the new product "Bücher- und Warenversand"

replace DPAG products "Büchersendung" and "Warensendung"

---

_includes/navs/examples_nav.html
_includes/reference/shipments_request_parameters.md
_includes/schemas/shipments_request.json
examples/index.md

and make sure to state that label.size is deprecated

add specification of label format

---

_config.yml
_includes/concepts/supported_services.html
_includes/navs/examples_nav.html
_sass/_layout.scss
examples/index.md

also introduced a third level navigation on examples page

added dpag warenpost international with signature

---

_data/carriers/go.json
_includes/examples/carriers/go/webservice/additional_services/delivery_date.html
_includes/examples/carriers/go/webservice/additional_services/delivery_time.html
_includes/schemas/shipments_request.json

- delivery_date
- delivery_time

added additional services for GO!

---

_config.yml
_data/carriers/gls.json
_includes/examples/carriers/gls/web_api/services/gls_express_0800.html
_includes/examples/carriers/gls/web_api/services/gls_express_0900.html
_includes/examples/carriers/gls/web_api/services/gls_express_1000.html
_includes/examples/carriers/gls/web_api/services/gls_express_1200.html
_includes/reference/shipment_quotes_request_parameters.html
_includes/reference/shipments_request_parameters.html
_includes/schemas/carriers_response.json
_includes/schemas/shipment_quotes_request.json
_includes/schemas/shipments_request.json

Also changed the way services are defined in the _config.yml to a list, so we can iterate over and adjust it in the frontend

added GLS express services

---

API_CHANGELOG.html
_includes/invoice_address_get_response.json
_includes/navs/reference_nav.html
_includes/schemas/invoice_address_response.json
reference/index.html
reference/invoice_address_response_schema.html
schemas/invoice_address_response.json

- default_returns_address
- default_shipping_address
- invoice_address

added new addresses endpoints

---

yarn.lock

also removes [this security alert](https://github.com/shipcloud/shipcloud.github.io/network/alert/yarn.lock/minimist/open)

updated js packages via yarn

---

API_CHANGELOG.html
_includes/examples/carriers/dhl/v2/additional_services/delivery_time.html

it will no longer be supported by DHL starting May 1 2020

deprecating the additional service delivery_time for DHL

---

_data/carriers/dpd.json
_includes/examples/carriers/dpd/shipment_service_4_3/additional_services/advance_notice.html
_includes/examples/carriers/dpd/shipment_service_4_3/additional_services/drop_authorization.html
_includes/examples/carriers/dpd/shipment_service_4_3/additional_services/food.html
_includes/examples/carriers/dpd/shipment_service_4_3/additional_services/saturday_delivery.html
_includes/examples/carriers/dpd/shipment_service_4_3/package_types/bulk.html
_includes/examples/carriers/dpd/shipment_service_4_3/package_types/parcel.html
_includes/examples/carriers/dpd/shipment_service_4_3/package_types/parcel_letter.html
_includes/examples/carriers/dpd/shipment_service_4_3/services/one_day.html
_includes/examples/carriers/dpd/shipment_service_4_3/services/one_day_early.html
_includes/examples/carriers/dpd/shipment_service_4_3/services/returns.html
_includes/examples/carriers/dpd/shipment_service_4_3/services/standard.html
_includes/schemas/shipments_request.json
carriers/dpd.html

This also introduces the new additional service DPD food

added new api version (4.3) for DPD

---

package.json
postcss.config.js
yarn.lock

[CSS nano website](https://cssnano.co/)

added postcss plugin cssnano

---

API_CHANGELOG.html
_data/carriers/dhl.json
_includes/examples/carriers/dhl/v3/additional_services/dhl_no_neighbor_delivery.html
_includes/examples/carriers/dhl/v3/additional_services/dhl_preferred_neighbor.html
_includes/examples/carriers/dhl/v3/additional_services/drop_authorization.html
_includes/schemas/shipments_request.json
_includes/schemas/shipments_response.json

- No neighbor delivery
- Preferred location
- Preferred neighbor

added DHL additional services

---

API_CHANGELOG.html
_data/carriers/dpd.json
_includes/examples/carriers/dpd/shipment_service_4_3/additional_services/hazardous_goods.html
_includes/schemas/shipments_request.json

added the additional service hazardous_goods for DPD
we currently only support one regulatory class and that is limited quantities

additional service hazardous_goods for DPD

---

API_CHANGELOG.html
_includes/navs/concepts_nav.html
concepts/index.html
downloads/api/oai/shipcloud_v1_oai3.json

added webhook security

---

downloads/api/oai/shipcloud_v1_oai3.json
package.json
yarn.lock

We add the recent changes to the Order API, like
`order_line_item#returnability`, to the Open API Schema.

Add recent order API changes to the OAS

---

README.md

This is only a minor part of Ticket 14057.
[sc-14057](https://app.shortcut.com/shipcloud/story/14057/timeboxed-2pt-developer-doku-bestandsaufnahme)

Add deployment segment to README.md

---

downloads/api/oai/shipcloud_v1_oai3.json

Also corrected the 400 response, which did not include the `errors` key.

Applied auto formatting to the OAS

---

downloads/api/oai/shipcloud_v1_oai3.json

Co-authored-by: Stephan Rodemeier <1868675+stphnrdmr@users.noreply.github.com>
[sc-17087](https://app.shortcut.com/shipcloud/story/17087)

Add pickup dropoff locations endpoint

---

concepts/index.html

There's a couple of unnecessary words in the docs. This PR removes them.

Reword the authentication documentation

---

concepts/index.html

[sc-33792](https://app.shortcut.com/shipcloud/story/33792)

Fix dimension types in multi colli request documentation

---

downloads/api/oai/shipcloud_v1_oai3.json

[sc-39329](https://app.shortcut.com/shipcloud/story/39329)

Add endpoints for shipment documents
