shipcloud/shipcloud-developer-portal

_includes/navs/reference_nav.html, _includes/shipments_index_response.json, reference/index.md
The API now provides access to the authenticated user's list of shipments,
allowing basic filtering and paging via HTTP query parameters.
This PR adds basic documentation for this node.
=> Adds documentation for node GET /shipments

_includes/shipments_index_response.json
Addresses always use ISO-3166 alpha-2 codes to identify a country. In the example response, the full country name 'Germany' has been used.
=> Replaces country name with ISO-3166 alpha-2 code in shipments response

_includes/samples/curl.html
This pull request adds a curl example for specifying drop authorization when using dpd as carrier
=> adding a curl sample for dpd drop authorization

_includes/navs/concepts_nav.html, concepts/index.md
We need to provide a little more information about why we're only sending minimal information about a shipment when a webhook gets fired.
=> Detailed webhooks information on concepts page

reference/index.md
We do not (as of now) support pickup requests for the carrier GLS - so we shouldn't mention GLS here.
=> Remove GLS from the list of carriers that support pickup requests

_includes/navs/concepts_nav.html, concepts/index.md
since the carrier web services can be slow from time to time we nee to be specific about timeouts when using the shipcloud api
=> added a tiny info about timeouts

_includes/schemas/shipments_request.json
implicitly stated that "additionalProperties" are true so readers can see directly that any content is allowed
=> added metadata to shipment object

_includes/reference/shipments_request_parameters.md, _includes/schemas/shipments_request.json, recipes/index.md
When creating a shipment with a package that has a type, the proper param name is type and not package_type.
=> Fix param name for package type

API_CHANGELOG.md
With this we'd like to document changes to our api so developers
have a simple overview about what changed since they've last taken
a look at our [api reference](https://developers.shipcloud.io/reference/).
=> added API_CHANGELOG.md

_includes/concepts/carrier_specific_label_sizes.html, _includes/concepts/supported_services.html, _includes/navs/concepts_nav.html, _includes/navs/recipes_nav.html, _includes/reference/shipments_request_parameters.md, _includes/schemas/shipments_request.json, concepts/index.md, recipes/index.md
Every carrier allows shipping labels to have different sizes. To make things even more complicated, the size can be different based on the service that's being used. Therefore we're now documenting,which label sizes are available for each carrier and the specific service.
We also added information and definitions about how you can define the label size when creating a shipping label through the shipcloud api.
=> added information about label sizes

API_CHANGELOG.md, _includes/pickup_post_requests_request.json, _includes/pickup_post_requests_response.json, _includes/reference/pickup_requests_request_parameters.md, _includes/schemas/pickup_requests_request.json, _includes/schemas/pickup_requests_response.json, reference/index.md
We're now supporting a **pickup_address** to be defined when sending a PickupRequest. This way our customers can define where the carrier should pick up their packages.
=> add pickup_address to PickupRequests

_includes/navs/concepts_nav.html, concepts/index.md, reference/index.md
The use of the parameter _description_ leads to confusion a lot of times, since it is a carrier and service based combination, when to add it and when not.
=> be more clear about the use of the description parameters

.firebaserc, firebase.json
Updates the firebase configuration to fix the following warnings:
* ⚠ "firebase" key in firebase.json is deprecated. Run firebase use --add instead
* ⚠ Deprecation Warning: Firebase Hosting configuration should be moved under "hosting" key.
=> Updates the firebase configuration

_includes/schemas/shipments_response_reduced.json, concepts/index.md
Since GLS is creating a tracking number once the shipping label is scanned for the first time, we can't return it in our response, when a shipment for the carrier is being created.
=> be more specific about gls shipments and carrier numbers

_includes/recipes/declared_value_dhl.md, _includes/shipments_post_put_request.json
To be more clear about the amount when you can/should use declared_value when creating a shipment, I've adjusted the exmaples to show a value higher than 500 Euros.
=> adjusted value in examples for declared_value

_includes/reference/shipment_quotes_request_parameters.md, _includes/schemas/shipment_quotes_request.json, _includes/shipment_quotes_post_request_with_address_id.json, reference/index.md
When creating a ShipmentQuote, one can define addresses by either supplying a full set of data or the id of an previously added address. You can also omit the from address completely if the user has defined a standard ship from address.
=> document address handling for ShipmentQuotes

_includes/reference/shipment_quotes_request_parameters.md, _includes/reference/shipments_request_parameters.md, _includes/schemas/shipment_quotes_request.json, _includes/schemas/shipments_request.json, _includes/shipments_post_request_with_pickup.json, concepts/index.md
- Some carriers require a pickup request to be send with the creation of
the shipping label. Therefore you can now send a pickup object with your
shipment request.
- We're also now supporting TNT as a new carrier
=> added reference and examples for shipments with pickup requests

API_CHANGELOG.md, _includes/concepts/webhooks_legend.html, _includes/schemas/shipments_response.json, _includes/shipments_index_response.json
=> remove shipment status "shipcloud_label_created" from eventy types

API_CHANGELOG.md, _includes/schemas/shipments_response.json, _includes/shipments_get_response.json
when reading a shipment, `shipper_notification_email` will now be returned (if specified during creation)
=> display shipper_notification_email when reading shipments

API_CHANGELOG.md, _config.yml, _includes/navs/reference_nav.html, _includes/reference/trackers_request_parameters.md, _includes/reference/trackers_request_togglebox.html, _includes/schemas/trackers_request.json, _includes/schemas/trackers_response.json, _includes/trackers_get_response.json, _includes/trackers_index_response.json, _includes/trackers_post_put_request.json, _includes/trackers_post_put_response.json, reference/index.md, reference/trackers_request_schema.md, reference/trackers_response_schema.md, schemas/trackers_request.json, schemas/trackers_response.json
Trackers make it possible to track a shipment that wasn't creating using shipcloud. They are basically a way to monitor shipments created elsewhere. All you have to do is provide us with the tracking number you received from the carrier as well as its corresponding name acronym.
=> added tracker ressource

API_CHANGELOG.md, _includes/schemas/trackers_response.json, _includes/trackers_get_response.json, _includes/trackers_index_response.json, _includes/trackers_post_put_response.json
As previously stated, we've replaced the deprecated parameter `tracking_code` with `carrier_tracking_no`. Tracker objects are using this parameter from now on.
=> replaced `tracking_code` with `carrier_tracking_no`

_includes/schemas/shipments_request.json, _includes/shipments_post_request_with_pickup_by_dhl_express.json, concepts/index.md
We've changed the way, DHL Express is integrated into our platform - since DHL Express in itself is a different service than DHL. This also makes it possible for customers to have a mix and match of DHL and DHL Express contracts within their account.
=> add DHL Express as a standalone carrier

_includes/concepts/carrier_specific_field_lengths_dhl.md, _includes/concepts/carrier_specific_field_lengths_dhl_express.md, _includes/concepts/carrier_specific_field_lengths_dpd.md, _includes/concepts/carrier_specific_field_lengths_go.md, _includes/concepts/carrier_specific_field_lengths_hermes_props.md, _includes/concepts/carrier_specific_field_lengths_tnt.md, concepts/index.md, index.html
To make it easier for readers to start developing for/with shipcloud we've updated the `Getting started` section on our homepage to make it clear that it doesn't need more than 3 steps to get started.
We've also found some incorrect values for carrier specific field lengths. And since I was already working at these entries I've added values for TNT which were missing until now.
=> update carrier specific field lengths and getting started

API_CHANGELOG.md, _includes/concepts/carrier_specific_field_lengths_dhl.md, _includes/navs/examples_nav.html, _includes/reference/shipments_request_parameters.md, _includes/schemas/shipcloud.json, _includes/schemas/shipments_request.json, examples/index.md
We're now supporting one of the most requested features: customs declarations for DHL.
By simply adding a few more parameters when creating a shipment with a shipping label you'll also get the customs forms back and are able to send your shipments to non EU countries.
=>  add dhl customs declaration information

_includes/schemas/trackers_response.json
Fixes "Error: Invalid type date-time in JSON Schema at schema#/properties/created_at."
In JSON Schema there is no such a type as `date-time`
http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2
Both https://app.quicktype.io and http://www.jsonschema2pojo.org/ failed to create Java POJO from this schema because of this syntax error. After my changes the conversion is successful.
=> fix syntax error

API_CHANGELOG.md, _includes/navs/reference_nav.html, _includes/pickup_requests_get_response.json, _includes/pickup_requests_index_response.json, _includes/schemas/pickup_requests_response.json, reference/index.md
If you want to know more about the separate pickup requests you've made you can now query our api to get a list of all of your pickup requests (`GET /v1/pickup_requests`) or details about a single one pickup_request (`GET /v1/pickup_requests/:id`)
=> Added api endpoints for querying pickup requests

API_CHANGELOG.md, _includes/navs/examples_nav.html, _includes/schemas/shipments_request.json, _includes/schemas/shipments_response.json, examples/index.md
You can now supply an incoterm code when sending shipments to dutiable countries (when using GLS).
=> add incoterm

_config.yml, _includes/schemas/shipments_response.json, _includes/schemas/trackers_response.json
Adds missing statuses to `Tracker` and `Shipment` schema.
Points to consider:
* The initial status of a Tracker is `registered`.
* The initial status of a shipment is `label_created`.
=> Update tracking events enum

API_CHANGELOG.html, _data/carriers/ups.json, _includes/examples/carriers/ups/ship_webservice/additional_services/ups_access_point_notification.html, _includes/examples/carriers/ups/ship_webservice/misc/access_point_delivery.html
This comes with a new additional service `ups_access_point_notification`
that can only be used when sending shipments to a UPS access point
=> added access point delivery for UPS

_includes/examples/carriers/dhl/v3/other_attributes/customs_declaration.html, _includes/examples/carriers/dhl/v3/services/returns.html
added new information about return shipments from Great Britain, since DHL now requires customs declaration data to be transmitted
=> DHL returns from GB

downloads/api/oai/shipcloud_v1_oai3.json
The correct link uses dashes instead of underscores.
=> Fix the terms and conditions link

README.md, _layouts/default_wide.html, swagger-ui/index.html
With the current two column layout, the OpenAPI spec swagger UI is too crammed to be able to read it. Tailwind allows us to set page specific layouts, though, so we provide a new wide layout without the right blue column and render the swagger UI with it.
=> Wide layout for OpenAPI spec template

_includes/schemas/trackers_request.json, _includes/schemas/trackers_response.json
Shipments have an attribute called metadata where customers can give us any kind of data they want as json.
We now want to allow this for Trackers as well.
Trackers is an endpoint for the send-core to create shipments that we do not create at the carrier but rather only have in our system to track them. 
Internally these are not a separate resource but rather a shipment with shipment_type: tracking_only.
To enable the use of metadata for those we need to add the functionality to the controller and builder for tracking_only shipments.
A customer should be able to create a Shipment with type tracking_only via the trackers endpoint that has metadata saved to it
Related PR: https://github.com/shipcloud/shipcloud/pull/9409
[sc-29308](https://app.shortcut.com/shipcloud/story/29308/allow-metadata …
=> Add metadata to trackers schema

_data/carriers/ups.json, concepts/index.html, downloads/api/oai/shipcloud_v1_oai3.json
With the capability in our API to book multi-packages for one shipment, we needed to implement some changes in the structure for our requests and responses.
- the package object is now a packages array which can have multiple packages dependent on the carrier
- The Create Shipment Response includes now the all the shipment attributes, similar to the GET Shipments call, and not only a few attributes
- When booking a shipment with a customs declaration, the customs declaration items need to be submitted on packages level and not in the customs declaration on shipment level anymore
In addition, the documentation for the `/rates` endpoint is being removed as this endpoint now has been removed altogether.
---
[sc-31618](https://app.shortcut.com/shipcloud/story/31618)
=> Change documentation for multi colli shipments
